config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :groups, only: [:index, :new, :create, :show, :destroy, :edit] do
    resources :operations, only: [:index, :new, :create, :show, :destroy, :edit]
  end
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do 
  
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end

  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_operations, dependent: :destroy
  has_many :operations, through: :group_operations

  validates :name, presence: true, length: { in: 3..250 }
  validates :icon, presence: true, length: { in: 3..250 }

  def total_amount
    operations.sum(:amount)
  end

  def recent_exchanges
    operations.order(created_at: :desc)
  end

  def self.created_by_current_user(current_user)
    where(user_id: current_user.id).order(created_at: :desc)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.created_by_current_user(current_user)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Category name", required: true, class: "input" %>
  </div>

  <div class="field">
    <%= form.text_field :icon, placeholder: "Icon URL", required: true, class: "input" %>
  </div>

  <div class="btn_block">
    <%= form.submit "Create Category", class: "btn_submit" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="category">
  <img class="image" src="<%= group.icon %>" alt=<%= group.name %>/>
  <p class="group-info"><%= group.name %></p>
  <p class="group-info">$<%= group.total_amount %></p>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<header>
<nav>
    <ul class="nav_list">
        <li class="nav-title"><%= current_user.name%></li>
        <li class="page_title">CATEGORIES</li>
        <% if user_signed_in? %>
        <li>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn"%>
        </li>
        <% else %>
        <li><%= button_to "Sign In", new_user_session_path, class: "nav-btn"  %></li>
        <% end %>
    </ul>
</nav>
</header>   
<p style="color: green"><%= notice %></p></br>

<div class="main_container">
  <% if @groups.empty? %>
    <p class="add_msg">Please add a new category</p>
  <% else %>
    <div id="groups" class="categories_container">
      <% @groups.each do |group| %>
        <% if can? :read, group %>
          <%= link_to group_operations_path(group.id), class:"group_text" do %>
            <%= render group %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
  <div class="btn_block"><%= link_to "Add Category", new_group_path, class: "btn_add" %></div>
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>