config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :groups, only: [:index, :new, :create, :show, :destroy, :edit] do
    resources :operations, only: [:index, :new, :create, :show, :destroy, :edit]
  end
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do 
  
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end

  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user

  has_many :group_operations, dependent: :destroy
  has_many :groups, through: :group_operations

  validates :name, :amount, presence: true, length: { in: 1..100 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_operation, only: %i[show edit update destroy]

  # GET /operations or /operations.json
  def index
    @group = current_user.groups.find(params[:group_id])
    @operations = @group.operations.order(created_at: :desc)
  end

  # GET /operations/1 or /operations/1.json
  def show; end

  # GET /operations/new
  def new
    @operation = Operation.new
    @group = Group.find(params[:group_id])
    @categories = Group.where(user_id: current_user.id)
  end

  # GET /operations/1/edit
  def edit; end

  # POST /operations or /operations.json
  def create
    params = operation_params
    @operation = Operation.new(name: params[:name], amount: params[:amount])
    @operation.user = current_user
    @categories_ids = params[:group_ids]
    @categories_ids.each do |id|
      group = Group.find(id) unless id == ''
      @operation.groups.push(group) unless group.nil?
    end

    respond_to do |format|
      if @operation.save
        format.html do
          redirect_to group_operations_path(@operation.groups.first.id), notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_operation
    @operation = Operation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def operation_params
    params.require(:operation).permit(:name, :amount, group_ids: [])
  end
end

app/views/operations/_form.html.erb
<%= form_with model: @operation, url: group_operations_path, method: :post, data: { turbo: false } do |form| %>
  <% if operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.text_field :name, placeholder: "Transaction name", required: true, class: "input" %>
  </div>
  
  <div class="field">
    <%= form.number_field :amount, placeholder: "Amount", required: true, class: "input", step: "any"  %>
  </div>

  <div class="field_checkbox">
  <%= form.label :you_can_choose_one_or_more_categories %> </br>
  <%= form.select :group_ids, @categories.collect {|category| [category.name, category.id]}, { include_blank: false }, required: true, multiple: true %>
  </div>

  <div class="btn_block">
  <%= form.submit "Create Transaction", class: "btn_submit" %>
</div>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>" class="operation">
  <p class="group-info"><%= operation.name %> </br> </br> 
  <span class="group-date"><%= operation.created_at.strftime("%d %b %Y") %></span>
  </p>
  <p class="group-info">$<%= operation.amount %></p>
</div>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @group_operation %> |
  <%= link_to "Back to operations", group_operations_path %>
</div>

app/views/operations/index.html.erb
<header>
<nav>
    <ul class="nav_list">
        <%= link_to "Back", groups_path, class: "nav-title" %>
        <li class="page_title">TRANSACTIONS</li>
        <% if user_signed_in? %>
        <li>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn"%>
        </li>
        <% else %>
        <li><%= button_to "Sign In", new_user_session_path, class: "nav-btn"  %></li>
        <% end %>
    </ul>
</nav>
</header> 
<p style="color: green"><%= notice %></p></br>

<div class="main_container">
<% if @operations.empty? %>
<p class="add_msg">Please add transactions</p>
<% else %>
    <div class="operations_total">
      <p><%= @group.name %></p>
      <p class="total_info">$<%= @operations.inject(0) { |sum, e| sum += e.amount  }%></p>
    </div>
    <div id="operations" class="operations_container">
    <% @operations.each do |operation| %>
      <%= link_to group_operation_path(@group.id, operation.id), class:"group_text" do %>
      <%= render operation %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="btn_block"><%= link_to "Add Transaction", new_group_operation_path, class: "btn_submit" %></div>
</div>

app/views/operations/new.html.erb
<header>
<nav>
    <ul class="nav_list">
        <%= link_to "Back", group_operations_path, class: "nav-title" %>
        <li class="page_title">ADD TRANSACTION</li>
        <% if user_signed_in? %>
        <li>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn"%>
        </li>
        <% else %>
        <li><%= button_to "Sign In", new_user_session_path, class: "nav-btn"  %></li>
        <% end %>
    </ul>
</nav>
</header> 

<%= render "form", operation: @operation %>

app/views/operations/show.html.erb
<header>
<nav>
    <ul class="nav_list">
        <%= link_to "Back", group_operations_path, class: "nav-title" %>
        <li class="page_title">TRANSACTION</li>
        <% if user_signed_in? %>
        <li>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn"%>
        </li>
        <% else %>
        <li><%= button_to "Sign In", new_user_session_path, class: "nav-btn"  %></li>
        <% end %>
    </ul>
</nav>
</header> 

<p style="color: green"><%= notice %></p></br>

<%= render @operation %>

<div class="btn_block">
  <%= button_to "Destroy this operation", @group_operations, method: :delete, class: "btn_delete"%>
</div>